name: build

on:
  workflow_call:
    inputs:
      jbang-trust-add:
        type: string
        default: ""

jobs:
  bughild:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup JBang
      uses: jbangdev/setup-jbang@main

    - name: Add trust
      if: inputs.jbang-trust-add != ''
      run: |
        jbang trust add ${{ inputs.jbang-trust-add }}

    - name: Install jq
      run: sudo apt-get install jq

    - name: Run JBang Tester
      run: |
        jbang trust add https://github.com/jbanghub/.github
        jbang https://github.com/jbanghub/.github/blob/main/.github/tester.java

